// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV2_frTOeoFJA13-MYBg8AfQYyWBuDTK0',
    appId: '1:164977897143:web:f047f9666410a75b3fe732',
    messagingSenderId: '164977897143',
    projectId: 'jenga-7e495',
    authDomain: 'jenga-7e495.firebaseapp.com',
    storageBucket: 'jenga-7e495.appspot.com',
    measurementId: 'G-EV8BKZ0D88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDG-_n1-fuprmES99xerPFeqWcMxHxSiM',
    appId: '1:164977897143:android:2c1d4e7bf4671dd33fe732',
    messagingSenderId: '164977897143',
    projectId: 'jenga-7e495',
    storageBucket: 'jenga-7e495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn2Q1LI2w9wqOiHkvyOkwAhyVr19566t4',
    appId: '1:164977897143:ios:6c1352c5ff44ca9d3fe732',
    messagingSenderId: '164977897143',
    projectId: 'jenga-7e495',
    storageBucket: 'jenga-7e495.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn2Q1LI2w9wqOiHkvyOkwAhyVr19566t4',
    appId: '1:164977897143:ios:6c1352c5ff44ca9d3fe732',
    messagingSenderId: '164977897143',
    projectId: 'jenga-7e495',
    storageBucket: 'jenga-7e495.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV2_frTOeoFJA13-MYBg8AfQYyWBuDTK0',
    appId: '1:164977897143:web:8318f385bc136dec3fe732',
    messagingSenderId: '164977897143',
    projectId: 'jenga-7e495',
    authDomain: 'jenga-7e495.firebaseapp.com',
    storageBucket: 'jenga-7e495.appspot.com',
    measurementId: 'G-KGKBXW7YES',
  );
}
